# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33c0844be729531efd9786f533b84b4317185dbcc21b7fdc7dbe595cc9dfae68fa6df624c52769b96eef3c64ffb8131b3df5080e34395456dfb935f9b9b0bcc2

test:
  secret_key_base: 5a198d980ca90f7597ca612336eb27b946951cd61a935147caef2dd1ec184a563763aea4aca0f3934e335963e6c1b20d52bac000e5e9d9724e18704098bd4f54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
